name: Test coverage CI (Any Branch)

on:
  # Run this workflow when you push to any branch
  push:
    branches: [ "*" ]

jobs:
  build:
    # Use the latest Ubuntu operating system for the runner
    runs-on: ubuntu-latest  # This is a virtual machine provided by GitHub
    steps:
      # Step 1: Download your repository code onto the runner
      - uses: actions/checkout@v4
      # Step 2: Set up R version 4.4.0 on the runner
      - name: Set up R
        uses: r-lib/actions/setup-r@v2 # check for latest version
        with:
          r-version: '4.4.0'
      # Step 3: Cache R packages to speed up future runs 
      - name: Set R_LIBS_USER
        run: echo "R_LIBS_USER=$(Rscript -e 'cat(.libPaths()[1])')" >> $GITHUB_ENV
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-
      # Step 4: Install all required R packages listed in DESCRIPTION
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::devtools  
      # Step 5: Run unit tests using devtools
      - name: Run tests
        run: Rscript -e 'devtools::test()'
      # Step 6: Generate coverage report with covr and upload as artifact
      
      - name: Run test coverage and generate reports
        run: |
          Rscript -e "cov <- covr::package_coverage(); \
                      covr::report(cov, file = 'coverage.html', browse = FALSE); \
                      writeLines(as.character(cov), 'coverage.txt')""
      - name: Upload coverage artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.txt
            coverage.html

